name: ItemStayReloaded
main: hugog.itemstay.Main
version: 1.0.0
description: Add static droped items to your server.
author: Hugo1307
api-version: 1.15

commands:
  isr:
    description: Main Command. 
